try {} catch(e) {
  print(e)
}

throw 25
